### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by warsaw**
Here's a new pull request based on our last round of discussions.  The previous PR was merged and then backed out.

### CODE REVIEW

**Comment by GMLudo** [comment]
Hi,

A chance that this PR will be integrated and pushed in Debian sid ?

Regards.

**Comment by warsaw** [comment]
On Jan 11, 2015, at 02:54 PM, Ludovic Gasc wrote:

>A chance that this PR will be integrated and pushed in Debian sid ?

I wish it could be, but I doubt it.  Jessie is in freeze and this would be a
new feature.  Also, I haven't heard anything from the maintainer about it, so
I don't even know if the patch is acceptable.  It's not a team maintained
package so I think the maintainer needs to chime in about his preferences.

**Comment by GMLudo** [comment]
I need this package, but if I understand, it's blocked since 6 months.
If the maintainer is a bottleneck, why this package couldn't be adopted by Python-Debian team to move forward ?

**Comment by warsaw** [comment]
On Jan 12, 2015, at 07:43 AM, Ludovic Gasc wrote:

>I need this package, but if I understand, it's blocked since 6 months.  If
>the maintainer is a bottleneck, why this package couldn't be adopted by
>Python-Debian team to move forward ?

I would certainly be willing to help with this package's maintenance if it was
under DPMT maintenance.  However, we can't just force the maintainer to do
that.  Ideally, the maintainer would offer to move it to DPMT[*] or give us
explicit permission to do so.  The alternatives as I understand them are to do
a NMU (only a one-time fix) or start MIA proceedings if the maintainer is no
longer active in Debian.  Neither of those latter two are appealing to me.

[*] If DPMT use of svn is an issue, please be aware that we have relaxed the
constraint such that we are allowing some packages to be maintained under git
on Alioth, using git-dpm.  At some point after Jessie we will likely mass
migrate DPMT pacakges from svn to git.

**Pull request closed without merging**
